### ISSUE TITLE
Connectivity issues to push data to MQTT

### ISSUE THREAD

**Issue by shifaz** [SensorsIot/Wi-Fi-Sniffer-as-a-Human-detector#10]
I'm having an issue where the sniffer cannot connect to AP on the second time, It goes to an infinite loop. 

I couldn't find any reason for this to happen. I have flashed this onto an NodeMCU v1.0 board.

**Comment by ghost** [comment]
same problem here with an wemos d1 mini

**Comment by shifaz** [comment]
Hello,

This issue is happening with ESP8266 SDK 2.3.0. The code works on older SDK. 

I was able to resolve the issues by following the instruction from [this thread ](https://github.com/esp8266/Arduino/issues/2186#issuecomment-228581052)

Basically, you need to modify the code as below.

```
WiFi.persistent(false);
WiFi.mode(WIFI_OFF);   // this is a temporary line, to be removed after SDK update to 1.5.4
WiFi.mode(WIFI_STA);
WiFi.begin(ssid, password);
```

**Comment by ghost** [comment]
thanks, good finding. works now with SDK 2.4.0.

**Comment by majodi** [comment]
Great! Everything works now, thank you. (I spent many hours trying to fix this...)
