### ISSUE TITLE
Can I have a MAC list pre-defined in the code?

### ISSUE THREAD

**Issue by kevinshane** [SensorsIot/Wi-Fi-Sniffer-as-a-Human-detector#11]
Hi Sir, thanks for your awesome job, the code is running very well!
However, the esp is constanly publishing many payloads and filled them all into my poor rpi mqtt server(around 100 msg per hour) and may have 3k+ msg per day!! I think this is huge and may crash the mqtt server(and the rpi sdcard maybe)
So, is that possible to have a few devices mac list pre-defined to codes and let the esp checking those mac if still can be seen, or if there is any other way to "reduce" the amount of those messages filled into the rpi?

**Comment by SensorsIot** [comment]
You can add it if you want. I have not plans for this code.
