### ISSUE TITLE
Watchdog crashes on NodeMCU 0.9 Core 2.4

### ISSUE THREAD

**Issue by Cloolalang** [SensorsIot/Wi-Fi-Sniffer-as-a-Human-detector#15]
This was an very quick and easy project to build, I have integrated mine with Hassio.
I noticed that my NodeMCU (8266) would crash after running a few hours with core 2.4.0.

I rolled it back to 2.3.0 and now its much more reliable.

Thanks for this really cool project and all the hard work you put in to it!

P

**Comment by SensorsIot** [comment]
Thank you for reporting this issue
