### ISSUE TITLE
New Json library version 6

### ISSUE THREAD

**Issue by stevenveenma** [SensorsIot/Wi-Fi-Sniffer-as-a-Human-detector#16]
Unfortunately this script uses the obsolete version 5 of the Json library. The current version 6 doesn't work with the script and the script needs to be adapted to the new version. This requires more than my knowledge of C++ to change the script.

**Comment by stevenveenma** [comment]
I installed an older version of the Json package now and get the sketch to work now.

**Comment by underwoodblog** [comment]
There are many scripts that aren't updated to use version 6.
