### ISSUE TITLE
Data transmitting issue

### ISSUE THREAD

**Issue by SudharsanK58** [SensorsIot/Wi-Fi-Sniffer-as-a-Human-detector#22]
The device is connecting to the wifi but the data is not being being transmitted via mqtt. The wifi is having internet connection and the mqtt broker is also connected.

**Comment by SensorsIot** [comment]
Maybe your broker is password protected?

**Comment by SudharsanK58** [comment]
Thanks for replay 

i found the issue its with wifi....But here is the real problem. "This sniffer does not detect most of mordern devices" why ideas ?

**Comment by SensorsIot** [comment]
Maybe they are on 5GHz?
