### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by nconder** [SensorsIot/Wi-Fi-Sniffer-as-a-Human-detector#4]
Thanks for this!
Please include or list dependencies.

**Comment by iEns** [comment]
I just compiled, and whatever it complained about I installed using the Library Manager in Arduino. Then it compiled without error.
I believe the missing dependencies were:
ESP8266
ArduinoJson
PubSubClient

**Comment by nconder** [comment]
@iEns thanks and yes adding those dependencies cleared things up. 

Adding these into the read me would be great to expedite deployments.

**Comment by SensorsIot** [comment]
Thanks. Done
