### ISSUE TITLE
Typo in WifiSniffer.ino

### ISSUE THREAD

**Issue by vince-br-549** [SensorsIot/Wi-Fi-Sniffer-as-a-Human-detector#6]
line 225
Serial.println("!!!!! Not published. please add #define MQTT_MAX_PACKET_SIZE 2048 at the beginning of pubSubClient.h file");

should say

Serial.println("!!!!! Not published. please add #define MQTT_MAX_PACKET_SIZE 2048 at the beginning of PubSubClient.h file");

**Comment by SensorsIot** [comment]
Done. Thanks.
