### ISSUE TITLE
PURGETIME and MINRSSI

### ISSUE THREAD

**Issue by joaofgf** [SensorsIot/Wi-Fi-Sniffer-as-a-Human-detector#7]
in the sendDevices() function, if the rssi is not bigger than the MINRSSI the device (beacon or client) will be excluded from the list immediatly, disregarding the PURGETIME value.

**Comment by SensorsIot** [comment]
Why would this be an issue?

**Comment by shifaz** [comment]
I'm having an issue where the sniffer cannot connect to AP on the second time, It goes to an infinite loop. 

I couldn't find any reason for this to happen. I have flashed this onto an NodeMCU v1.0 board.
