### ISSUE TITLE
Changes to enhance readability

### ISSUE THREAD

**Issue by vince-br-549** [SensorsIot/Wi-Fi-Sniffer-as-a-Human-detector#8]
What a great sketch.  I'm having a great time trying to figure out the results.

The following changes are minor and just enhance the serial output.
Fo example it occasionally displays a message like
Client 6 removed
which immediately scrolls off the screen while I try to count down to see which want it was.
So I added a number to the left side of the report to make it fast to see which was client 6 :)

LIne 150 replaced:
     Serial.println(aps_known_count + clients_known_count);
with
      Serial.printf("%4d Devices + Clients.\n",aps_known_count + clients_known_count);  // show count

LIne 152 replaced:
 // add Beacons
with
 // show Beacons

Line 154 replaced:
 Serial.print("B ");
with
Serial.printf( "%4d ",u);  // Show beacon number
 Serial.print("B ");

Line 162 Replaced:
// add Clients 
to
// show Clients

Line 164 Replaced:
 Serial.print("C ");
with
Serial.printf("%4d ",u);  // Show client number
 Serial.print("C ");

Line 186 replaced
       Serial.print("failed with state ");
       Serial.print(client.state());
with
      Serial.print("failed with state " );
       Serial.println(client.state());

and lastly changed pubSubClient.h to PubSubClient.h

**Comment by SensorsIot** [comment]
Thanks. Should be there now.
