### ISSUE TITLE
Speed Issue

### ISSUE THREAD

**Issue by badlandz** [SensorsIot/Wi-Fi-Sniffer-as-a-Human-detector#9]
I have tried this out with a Wemos D1, and it works alright, at first. But on the second attempt to connect to my WIFI to send to MQTT server, it never connects again. I do not think it is an issue with the program or Arduino, it's probably my network.

However, in my attempt to think of a "work around" to the problem, I had an idea that I have not yet tried. What if, to improve speed, rather than use multiple ESP12E chips, just use 2 chips? First chip scans wifi continuously, and never attempts to stop scanning to link to the WAP2 network, saving time, and sending data via serial or I2C to the second chip. The second chip is always connected to the local LAN, and never needs to disconnect/reconnect, and reads data from first chip and transmits to the MQTT server?

**Comment by SensorsIot** [comment]
This for sure can be done. I am not sure if the work is worth the effort because during my tests the biggest delay came from the Smartphones themselves. They did not send their MAC address too often.
